# https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx
# https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
controller:
  replicaCount: 3
  nodeSelector:
    kubernetes.io/os: linux
    agentpool: user # b/c omsagent hogs system node
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /livez
    externalTrafficPolicy: Local
  topologySpreadConstraints:
  - maxSkew: 2
    topologyKey: "kubernetes.io/hostname" # spread evenly across nodes
    whenUnsatisfiable: DoNotSchedule # or ScheduleAnyway
    labelSelector:
      matchLabels:
        app: ingress
  podLabels:
    app: ingress
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: ${AKS_RG_NAME}
    loadBalancerIP: ${INGRESS_STATIC_IP}
  extraArgs:
    default-ssl-certificate: "ingress/ingress-tls-${AKS_ENV_NAME}-wildcard"
  extraVolumes:
      - name: cluster-kv-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "cluster-kv"
      - name: ingress-tls-${AKS_ENV_NAME}-wildcard
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "ingress-tls-${AKS_ENV_NAME}-wildcard"
  extraVolumeMounts:
      - name: cluster-kv-inline
        mountPath: "/mnt/cluster-kv"
        readOnly: true
      - name: ingress-tls-${AKS_ENV_NAME}-wildcard
        mountPath: "/mnt/ingress-tls-wildcard"
        readOnly: true
defaultBackend:
  nodeSelector:
    kubernetes.io/os: linux
    agentpool: user # b/c omsagent hogs system node
