apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  namespace: hello-world
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - '${AKS_ENV_HOSTNAME}' # 'dev.cloudkube.io'
    secretName: ingress-tls-${AKS_ENV_NAME}
  rules:
    - host: ${AKS_ENV_HOSTNAME} # dev.cloudkube.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world
                port:
                  number: 80
