apiVersion: approuting.kubernetes.azure.com/v1alpha1
kind: NginxIngressController
metadata:
  name: nginx-static
spec:
  ingressClassName: nginx-static
  controllerNamePrefix: nginx-static
  loadBalancerAnnotations:
    service.beta.kubernetes.io/azure-pip-name: "cloudkube-dev-ingress-ip"
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "cloudkube-dev-3bm0-managed-rg"